---
- name: IOS ACLs
  hosts: rtr1
  tasks:
    - name: TEST "{{state}}"ed ACLS
      cisco.ios.ios_acls:
        state: "{{ state }}"
      register: result
    - debug:
        msg: "{{ result.state }}"
