---
- name: IOS ACLs
  hosts: rtr1
  gather_facts: no
  tasks:
    - name: GATHER  ACLS
      cisco.ios.ios_acls:
        state: gathered
      register: result
    - debug:
        msg: "{{ result.gathered }}"
