---
- name: MULTIVENDOR SYSTEM CONFIGS
  hosts: cisco, arista
  gather_facts: false
  tags: configure

  tasks:
    - name: ENSURE THAT THE HOSTNAME AND DOMAIN NAME ARE SET
      include_tasks: "{{ ansible_network_os }}_host.yaml"

- name: MULTIVENDOR SYSTEM CONFIGS
  hosts: cisco, arista
  gather_facts: false
  tags: revert

  tasks:
    - name: ENSURE THAT THE HOSTNAME AND DOMAIN NAME ARE SET
      include_tasks: "{{ ansible_network_os }}_remove.yaml"
