---
- name: MULTIVENDOR SYSTEM CONFIGS
  hosts: cisco, arista
  gather_facts: false

  tasks:
    - name: ENSURE THAT THE SYSTEM CONFIGS ARE PRESENT
      include_tasks:
        file: "{{ ansible_network_os }}_host.yaml"
        apply:
          tags: configure

    - name: ENSURE THAT THE SYSTEM CONFIGS ARE ABSENT
      include_tasks:
        file: "{{ ansible_network_os }}_remove.yaml"
        apply:
          tags: revert
