---
- name: MULTIVENDOR SYSTEM CONFIGS
  hosts: cisco, arista
  gather_facts: false

  tasks:
    - name: ENSURE THAT THE SYSTEM CONGIGS ARE PRESENT
      include_tasks: "{{ ansible_network_os }}_host.yaml"
      tags: configure

    - name: ENSURE THAT THE SYSTEM CONFIGS ARE ABSENT
      include_tasks: "{{ ansible_network_os }}_remove.yaml"
      tags: revert
