---
- name: JUNOS MODULE TO REMOVE SYSTEM CONFIGS
  hosts: juniper
  gather_facts: false

  tasks:
    - name: ENSURE THAT THE SYSTEM CONFIGS ARE REMOVED
      junos_system:
        state: absent
        domain_name:
        domain_search:
    - name: ENSURE THAT THE SYSTEM CONFIGS ARE REMOVED
      junos_system:
        state: absent
        name_servers:
          - 192.168.1.1
          - 3.3.3.3
          - 8.8.8.8
          - 1.1.1.1
