---
- name: Tower Caching behaviour
  hosts: rtr2,rtr4
  gather_facts: no
  tags: normal
  
  tasks:
    - include_vars: vars/interface_vars.yaml
    - eos_facts:
        gather_subset: "!config"

    - meta: clear_facts

    - debug: var=ansible_net_interfaces
      

       

    

# - name: Tower Caching behaviour
#   hosts: rtr2, rtr4
#   gather_facts: no
#   tags: purge

#   tasks:
#     - eos_facts:
#         gather_subset: "!config"

#     - meta: clear_facts
      
