---
- name: TOWER CACHING BEHAVIOR
  hosts: rtr2,rtr4
  gather_facts: no
  tags: normal
  
  tasks:
    - name: DOWNLOAD VARS FROM EXTERNAL REPO
      git:
        repo: https://github.com/termlen0/vars_repo
        dest: varsdir
      run_once: true
      delegate_to: localhost
        
    - name: INCLUDE THE VARS WITHIN THE PLAY
      include_vars:
        dir: varsdir
        depth: 1
        extensions:
          - yaml
      delegate_to: localhost
      run_once: true

    - name: SHOW THE VALUE OF ONE OF THE VARS
      debug: var=ospf_area

    - name: SHOW THE VALUE OF ANOTHER VAR
      debug: var=backbone.tunnel_network

    - name: STAT THE DIR TO ENSURE IT EXITS
      stat:
        path: varsdir
      register: p
      run_once: true
      delegate_to: localhost

      
    - name: DISPLAY OUTPUT BASED ON STAT
      debug:
        msg: "Path exists and is a directory"
      when: p.stat.isdir is defined and p.stat.isdir
      run_once: true
       
      
    - name: COLLECT DEVICE FACTS
      eos_facts:
        gather_subset: "!config"

    - name: REMOVE THE DOWNLOADED VARS DIR
      file:
        path: varsdir
        state: absent
      delegate_to: localhost
      run_once: true

    - name: REDO THE DIR STAT TO CHECK IF DIR EXISTS
      stat:
        path: varsdir
      register: p
      run_once: true
      delegate_to: localhost

    - name: DISPLAY OUTPUT BASED ON STAT
      debug:
        msg: "Path no longer exists!!"
      when:  p.stat.isdir is not defined 
      run_once: true
      delegate_to: localhost
    
