---
- name: Tower Caching behaviour
  hosts: rtr2,rtr4
  gather_facts: no
  tags: normal
  
  tasks:
    - git:
        repo: https://github.com/termlen0/vars_repo
        dest: varsdir
        
    - include_vars:
        file: varsdir/common.yaml
        #depth: 1
        

    - debug: var=ospf_area

    - command: ls -l varsdir
        
      
    - eos_facts:
        gather_subset: "!config"

    - file:
        path: varsdir
        state: absent

    - command: ls -l varsdir

        
   # - meta: clear_facts

    #- debug: var=ansible_net_interfaces
      

       

    

# - name: Tower Caching behaviour
#   hosts: rtr2, rtr4
#   gather_facts: no
#   tags: purge

#   tasks:
#     - eos_facts:
#         gather_subset: "!config"

#     - meta: clear_facts
      
