---
- name: Tower Caching behaviour
  hosts: rtr2,rtr4
  gather_facts: no
  tags: normal
  
  tasks:
    - git:
        repo: https://github.com/termlen0/vars_repo
        dest: varsdir
      run_once: true
      delegate_to: localhost
        
    - include_vars:
        dir: varsdir
        depth: 1
        extensions:
          - yaml

    - debug: var=ospf_area

    - stat:
        path: varsdir
      register: p
      
    - debug:
        msg: "Path exists and is a directory"
      when: p.stat.isdir is defined and p.stat.isdir
             
      
    - eos_facts:
        gather_subset: "!config"

    - file:
        path: varsdir
        state: absent
      delegate_to: localhost
      run_once: true

    - stat:
        path: varsdir
      register: p
      
    - debug:
        msg: "Path no longer exists and is a directory"
      when: not p.stat.isdir is defined and p.stat.isdir
    
