---
- name: Tower Caching behaviour
  hosts: rtr2,rtr4
  gather_facts: no
  tags: normal

  tasks:
    - include_vars: vars/interface_vars.yaml

    - debug: var=interfaces.loopbacks

    - eos_facts:
        gather_subset: "!config"
          

    


- name: Tower Caching behaviour
  hosts: all
  gather_facts: no
  tags: purge

  tasks:
    - include_vars: vars/interface_vars.yaml

    - debug: var=interfaces.loopbacks

    - eos_facts:
        gather_subset: "!config"


    - meta: clear_facts
      
