---
- name: Tower Caching behaviour
  hosts: rtr2,rtr4
  tasks:
    # - include_vars: vars/interface_vars.yaml

    # - debug: var=interfaces.loopbacks

    - eos_facts:

    # - debug: var=hostvars[inventory_hostname]
          

    # - template:
    #     src: simple.j2
    #     dest: "{{ inventory_hostname }}.md"
        
- name: Caching for JUNOS
  hosts: rtr3

  tasks:
    - junos_facts:
        gather_subset: "!config"

    # - debug: var=hostvars[inventory_hostname]

    # - template:
    #     src: simple.j2
    #     dest: "{{ inventory_hostname }}.md"

- name: Caching for IOS
  hosts: rtr1

  tasks:
    - ios_facts:
        gather_subset: "!config"

    # - debug: var=hostvars[inventory_hostname]

    # - template:
    #     src: simple.j2
    #     dest: "{{ inventory_hostname }}.md"
    


# - name: Tower Caching behaviour
#   hosts: all
#   gather_facts: no
#   tags: purge

#   tasks:
#     - include_vars: vars/interface_vars.yaml

#     - debug: var=interfaces.loopbacks
#     - eos_facts:

#     - meta: clear_facts
      
