---
- name: Configure NSO from Ansible
  hosts: localhost
  gather_facts: no

  vars:
    nso_server: 192.168.1.250
    username: "admin"
    password: "admin"
    url: "http://{{ nso_server }}:8080/jsonrpc"
    perform_backup: no


  tasks:

    - name: Add a new SNMP RO community string
      nso_config:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        data:
          tailf-ncs:services:
            nso-snmp:nso-snmp:
              - snmp_ro: "{{ input_snmp_ro | default("joonsnmp" )}}"
                nso-snmp:device:
                  - "{{ nso_device : default("rtr0") }}"
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync
