---
- name: Sync from device
  hosts: rtr1
  gather_facts: no
  tags: sync_from
  vars:
    username: "admin"
    password: "admin"
    nso_server: 192.168.1.250
    url: "http://{{ nso_server }}:8080/jsonrpc"
    perform_backup: no


  tasks:

    - name: Sync from one device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/sync-from
        input: { 'device': [rtr0,rtr1,rtr2] }
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync

    - name: Check all sync
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/check-sync
        input: { 'device' : [rtr0,rtr1,rtr2]}
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync



- name: Sync to device
  hosts: rtr1
  gather_facts: no
  tags: sync_to
  tasks:
    - name: Sync to a specific device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/sync-to
        input: { "device": [rtr0,rtr1,rtr2] }
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync
