---
- name: Update BGP
  hosts: rtr1
  gather_facts: no
  tasks:
    - name: Advertise a new subnet
      ios_bgp:
        config:
           bgp_as: "{{ asn }}"
           networks:
             - prefix: "{{ subnet | ipaddr('network') }}"
               masklen: "{{ subnet| ipaddr('prefix') }}"
        operation: merge
