---
- name: Some NSO fun
  hosts: localhost
  gather_facts: no

  vars:
    nso_server: 192.168.1.250
    username: "admin"
    password: "admin"
    url: "http://{{ nso_server }}:8080/jsonrpc"
    perform_backup: no


  tasks:
    - name: Check all sync
      nso_show:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/device
        operational: true
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync
