---
- name: Some NSO fun
  hosts: localhost
  gather_facts: no

  vars:
    username: "admin"
    password: "admin"
    url: "http://127.0.0.1:8080/jsonrpc"
    perform_backup: no


  tasks:
    - name: Check all sync
      nso_show:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/device
        operational: true
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync
